### PR TITLE
[WIP] Add CuPy backend

### PR DESCRIPTION
**Pull request by leofang**
This PR is an experimental work demonstrating how easy a NumPy code can be ported to CuPy that runs on NVIDIA GPUs. This is still a WIP as `fftautocorr` is awfully slow; `multitau` seems OK. If there is interest I can work on polishing and optimizing the code, adding CuPy to `setup.py` as an optional dependency, etc.

### CODE REVIEW

**Comment by danielballan** [comment]
Oh, nice! I just noticed this PR. This seems interesting to me! I did the same for a dask-based version that I need to open a PR for.

Would be great if you could keep pressing on this when you have time.

**Comment by leofang** [comment]
Looks like we won't need this PR once #15 is resolved. Closing this for now...

**Comment by leofang** [comment]
> Looks like we won't need this PR once #15 is resolved. Closing this for now...

Note to myself: I am not saying the current NumPy-based implementation is also performant with CuPy. I am not sure what's the typical data size to be processed, so if this is a concern, we'll still need a specialized GPU version.

**Comment by leofang** [comment]
Superseded by #17.

**Pull request closed without merging**
